// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  type Options as Options2,
  type TDataShape,
  urlSearchParamsBodySerializer,
} from "./client";
import {
  AcceptOAuth2ConsentRequestRequestSchema,
  AcceptOAuth2ConsentRequestResponseSchema,
  AcceptOAuth2LoginRequestRequestSchema,
  AcceptOAuth2LoginRequestResponseSchema,
  AcceptOAuth2LogoutRequestRequestSchema,
  AcceptOAuth2LogoutRequestResponseSchema,
  CreateJsonWebKeySetRequestSchema,
  CreateJsonWebKeySetResponseSchema,
  CreateOAuth2ClientRequestSchema,
  CreateOAuth2ClientResponseSchema,
  DeleteJsonWebKeyRequestSchema,
  DeleteJsonWebKeyResponseSchema,
  DeleteJsonWebKeySetRequestSchema,
  DeleteJsonWebKeySetResponseSchema,
  DeleteOAuth2ClientRequestSchema,
  DeleteOAuth2ClientResponseSchema,
  DeleteOAuth2TokenRequestSchema,
  DeleteOAuth2TokenResponseSchema,
  DeleteTrustedOAuth2JwtGrantIssuerRequestSchema,
  DeleteTrustedOAuth2JwtGrantIssuerResponseSchema,
  GetJsonWebKeyRequestSchema,
  GetJsonWebKeyResponseSchema,
  GetJsonWebKeySetRequestSchema,
  GetJsonWebKeySetResponseSchema,
  GetOAuth2ClientRequestSchema,
  GetOAuth2ClientResponseSchema,
  GetOAuth2ConsentRequestRequestSchema,
  GetOAuth2ConsentRequestResponseSchema,
  GetOAuth2LoginRequestRequestSchema,
  GetOAuth2LoginRequestResponseSchema,
  GetOAuth2LogoutRequestRequestSchema,
  GetOAuth2LogoutRequestResponseSchema,
  GetTrustedOAuth2JwtGrantIssuerRequestSchema,
  GetTrustedOAuth2JwtGrantIssuerResponseSchema,
  GetVersionRequestSchema,
  GetVersionResponseSchema,
  IntrospectOAuth2TokenRequestSchema,
  IntrospectOAuth2TokenResponseSchema,
  IsAliveRequestSchema,
  IsAliveResponseSchema,
  IsReadyRequestSchema,
  IsReadyResponseSchema,
  ListOAuth2ClientsRequestSchema,
  ListOAuth2ClientsResponseSchema,
  ListOAuth2ConsentSessionsRequestSchema,
  ListOAuth2ConsentSessionsResponseSchema,
  ListTrustedOAuth2JwtGrantIssuersRequestSchema,
  ListTrustedOAuth2JwtGrantIssuersResponseSchema,
  PatchOAuth2ClientRequestSchema,
  PatchOAuth2ClientResponseSchema,
  RejectOAuth2ConsentRequestRequestSchema,
  RejectOAuth2ConsentRequestResponseSchema,
  RejectOAuth2LoginRequestRequestSchema,
  RejectOAuth2LoginRequestResponseSchema,
  RejectOAuth2LogoutRequestRequestSchema,
  RejectOAuth2LogoutRequestResponseSchema,
  RevokeOAuth2ConsentSessionsRequestSchema,
  RevokeOAuth2ConsentSessionsResponseSchema,
  RevokeOAuth2LoginSessionsRequestSchema,
  RevokeOAuth2LoginSessionsResponseSchema,
  SetJsonWebKeyRequestSchema,
  SetJsonWebKeyResponseSchema,
  SetJsonWebKeySetRequestSchema,
  SetJsonWebKeySetResponseSchema,
  SetOAuth2ClientLifespansRequestSchema,
  SetOAuth2ClientLifespansResponseSchema,
  SetOAuth2ClientRequestSchema,
  SetOAuth2ClientResponseSchema,
  TrustOAuth2JwtGrantIssuerRequestSchema,
  TrustOAuth2JwtGrantIssuerResponseSchema,
} from "./schemas";
import type {
  AcceptOAuth2ConsentRequestErrors,
  AcceptOAuth2ConsentRequestRequest,
  AcceptOAuth2ConsentRequestResponses,
  AcceptOAuth2LoginRequestErrors,
  AcceptOAuth2LoginRequestRequest,
  AcceptOAuth2LoginRequestResponses,
  AcceptOAuth2LogoutRequestErrors,
  AcceptOAuth2LogoutRequestRequest,
  AcceptOAuth2LogoutRequestResponses,
  CreateJsonWebKeySetErrors,
  CreateJsonWebKeySetRequest,
  CreateJsonWebKeySetResponses,
  CreateOAuth2ClientErrors,
  CreateOAuth2ClientRequest,
  CreateOAuth2ClientResponses,
  DeleteJsonWebKeyErrors,
  DeleteJsonWebKeyRequest,
  DeleteJsonWebKeyResponses,
  DeleteJsonWebKeySetErrors,
  DeleteJsonWebKeySetRequest,
  DeleteJsonWebKeySetResponses,
  DeleteOAuth2ClientErrors,
  DeleteOAuth2ClientRequest,
  DeleteOAuth2ClientResponses,
  DeleteOAuth2TokenErrors,
  DeleteOAuth2TokenRequest,
  DeleteOAuth2TokenResponses,
  DeleteTrustedOAuth2JwtGrantIssuerErrors,
  DeleteTrustedOAuth2JwtGrantIssuerRequest,
  DeleteTrustedOAuth2JwtGrantIssuerResponses,
  GetJsonWebKeyErrors,
  GetJsonWebKeyRequest,
  GetJsonWebKeyResponses,
  GetJsonWebKeySetErrors,
  GetJsonWebKeySetRequest,
  GetJsonWebKeySetResponses,
  GetOAuth2ClientErrors,
  GetOAuth2ClientRequest,
  GetOAuth2ClientResponses,
  GetOAuth2ConsentRequestErrors,
  GetOAuth2ConsentRequestRequest,
  GetOAuth2ConsentRequestResponses,
  GetOAuth2LoginRequestErrors,
  GetOAuth2LoginRequestRequest,
  GetOAuth2LoginRequestResponses,
  GetOAuth2LogoutRequestErrors,
  GetOAuth2LogoutRequestRequest,
  GetOAuth2LogoutRequestResponses,
  GetTrustedOAuth2JwtGrantIssuerErrors,
  GetTrustedOAuth2JwtGrantIssuerRequest,
  GetTrustedOAuth2JwtGrantIssuerResponses,
  GetVersionRequest,
  GetVersionResponses,
  IntrospectOAuth2TokenErrors,
  IntrospectOAuth2TokenRequest,
  IntrospectOAuth2TokenResponses,
  IsAliveErrors,
  IsAliveRequest,
  IsAliveResponses,
  IsReadyErrors,
  IsReadyRequest,
  IsReadyResponses,
  ListOAuth2ClientsErrors,
  ListOAuth2ClientsRequest,
  ListOAuth2ClientsResponses,
  ListOAuth2ConsentSessionsErrors,
  ListOAuth2ConsentSessionsRequest,
  ListOAuth2ConsentSessionsResponses,
  ListTrustedOAuth2JwtGrantIssuersErrors,
  ListTrustedOAuth2JwtGrantIssuersRequest,
  ListTrustedOAuth2JwtGrantIssuersResponses,
  PatchOAuth2ClientErrors,
  PatchOAuth2ClientRequest,
  PatchOAuth2ClientResponses,
  RejectOAuth2ConsentRequestErrors,
  RejectOAuth2ConsentRequestRequest,
  RejectOAuth2ConsentRequestResponses,
  RejectOAuth2LoginRequestErrors,
  RejectOAuth2LoginRequestRequest,
  RejectOAuth2LoginRequestResponses,
  RejectOAuth2LogoutRequestErrors,
  RejectOAuth2LogoutRequestRequest,
  RejectOAuth2LogoutRequestResponses,
  RevokeOAuth2ConsentSessionsErrors,
  RevokeOAuth2ConsentSessionsRequest,
  RevokeOAuth2ConsentSessionsResponses,
  RevokeOAuth2LoginSessionsErrors,
  RevokeOAuth2LoginSessionsRequest,
  RevokeOAuth2LoginSessionsResponses,
  SetJsonWebKeyErrors,
  SetJsonWebKeyRequest,
  SetJsonWebKeyResponses,
  SetJsonWebKeySetErrors,
  SetJsonWebKeySetRequest,
  SetJsonWebKeySetResponses,
  SetOAuth2ClientErrors,
  SetOAuth2ClientLifespansErrors,
  SetOAuth2ClientLifespansRequest,
  SetOAuth2ClientLifespansResponses,
  SetOAuth2ClientRequest,
  SetOAuth2ClientResponses,
  TrustOAuth2JwtGrantIssuerErrors,
  TrustOAuth2JwtGrantIssuerRequest,
  TrustOAuth2JwtGrantIssuerResponses,
} from "./types";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

class HeyApiClient {
  protected client: Client;

  constructor(args: { client: Client }) {
    this.client = args.client;
  }
}

class HeyApiRegistry<T> {
  private readonly defaultKey = "default";

  private readonly instances: Map<string, T> = new Map();

  get(key?: string): T {
    const instance = this.instances.get(key ?? this.defaultKey);
    if (!instance) {
      throw new Error(
        `No SDK client found. Create one with "new Sdk()" to fix this error.`,
      );
    }
    return instance;
  }

  set(value: T, key?: string): void {
    this.instances.set(key ?? this.defaultKey, value);
  }
}

export class Sdk extends HeyApiClient {
  public static readonly __registry = new HeyApiRegistry<Sdk>();

  constructor(args: { client: Client; key?: string }) {
    super(args);
    Sdk.__registry.set(this, args.key);
  }

  /**
   * List OAuth 2.0 Clients
   *
   * This endpoint lists all clients in the database, and never returns client secrets.
   * As a default it lists the first 100 clients.
   */
  public listOAuth2Clients<ThrowOnError extends boolean = false>(
    options?: Options<ListOAuth2ClientsRequest, ThrowOnError>,
  ) {
    return (options?.client ?? this.client).get<
      ListOAuth2ClientsResponses,
      ListOAuth2ClientsErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await ListOAuth2ClientsRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await ListOAuth2ClientsResponseSchema.parseAsync(data),
      url: "/admin/clients",
      ...options,
    });
  }

  /**
   * Create OAuth 2.0 Client
   *
   * Create a new OAuth 2.0 client. If you pass `client_secret` the secret is used, otherwise a random secret
   * is generated. The secret is echoed in the response. It is not possible to retrieve it later on.
   */
  public createOAuth2Client<ThrowOnError extends boolean = false>(
    options: Options<CreateOAuth2ClientRequest, ThrowOnError>,
  ) {
    return (options.client ?? this.client).post<
      CreateOAuth2ClientResponses,
      CreateOAuth2ClientErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await CreateOAuth2ClientRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await CreateOAuth2ClientResponseSchema.parseAsync(data),
      url: "/admin/clients",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Delete OAuth 2.0 Client
   *
   * Delete an existing OAuth 2.0 Client by its ID.
   *
   * OAuth 2.0 clients are used to perform OAuth 2.0 and OpenID Connect flows. Usually, OAuth 2.0 clients are
   * generated for applications which want to consume your OAuth 2.0 or OpenID Connect capabilities.
   *
   * Make sure that this endpoint is well protected and only callable by first-party components.
   */
  public deleteOAuth2Client<ThrowOnError extends boolean = false>(
    options: Options<DeleteOAuth2ClientRequest, ThrowOnError>,
  ) {
    return (options.client ?? this.client).delete<
      DeleteOAuth2ClientResponses,
      DeleteOAuth2ClientErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await DeleteOAuth2ClientRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await DeleteOAuth2ClientResponseSchema.parseAsync(data),
      url: "/admin/clients/{id}",
      ...options,
    });
  }

  /**
   * Get an OAuth 2.0 Client
   *
   * Get an OAuth 2.0 client by its ID. This endpoint never returns the client secret.
   *
   * OAuth 2.0 clients are used to perform OAuth 2.0 and OpenID Connect flows. Usually, OAuth 2.0 clients are
   * generated for applications which want to consume your OAuth 2.0 or OpenID Connect capabilities.
   */
  public getOAuth2Client<ThrowOnError extends boolean = false>(
    options: Options<GetOAuth2ClientRequest, ThrowOnError>,
  ) {
    return (options.client ?? this.client).get<
      GetOAuth2ClientResponses,
      GetOAuth2ClientErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await GetOAuth2ClientRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await GetOAuth2ClientResponseSchema.parseAsync(data),
      url: "/admin/clients/{id}",
      ...options,
    });
  }

  /**
   * Patch OAuth 2.0 Client
   *
   * Patch an existing OAuth 2.0 Client using JSON Patch. If you pass `client_secret`
   * the secret will be updated and returned via the API. This is the
   * only time you will be able to retrieve the client secret, so write it down and keep it safe.
   *
   * OAuth 2.0 clients are used to perform OAuth 2.0 and OpenID Connect flows. Usually, OAuth 2.0 clients are
   * generated for applications which want to consume your OAuth 2.0 or OpenID Connect capabilities.
   */
  public patchOAuth2Client<ThrowOnError extends boolean = false>(
    options: Options<PatchOAuth2ClientRequest, ThrowOnError>,
  ) {
    return (options.client ?? this.client).patch<
      PatchOAuth2ClientResponses,
      PatchOAuth2ClientErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await PatchOAuth2ClientRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await PatchOAuth2ClientResponseSchema.parseAsync(data),
      url: "/admin/clients/{id}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Set OAuth 2.0 Client
   *
   * Replaces an existing OAuth 2.0 Client with the payload you send. If you pass `client_secret` the secret is used,
   * otherwise the existing secret is used.
   *
   * If set, the secret is echoed in the response. It is not possible to retrieve it later on.
   *
   * OAuth 2.0 Clients are used to perform OAuth 2.0 and OpenID Connect flows. Usually, OAuth 2.0 clients are
   * generated for applications which want to consume your OAuth 2.0 or OpenID Connect capabilities.
   */
  public setOAuth2Client<ThrowOnError extends boolean = false>(
    options: Options<SetOAuth2ClientRequest, ThrowOnError>,
  ) {
    return (options.client ?? this.client).put<
      SetOAuth2ClientResponses,
      SetOAuth2ClientErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await SetOAuth2ClientRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await SetOAuth2ClientResponseSchema.parseAsync(data),
      url: "/admin/clients/{id}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Set OAuth2 Client Token Lifespans
   *
   * Set lifespans of different token types issued for this OAuth 2.0 client. Does not modify other fields.
   */
  public setOAuth2ClientLifespans<ThrowOnError extends boolean = false>(
    options: Options<SetOAuth2ClientLifespansRequest, ThrowOnError>,
  ) {
    return (options.client ?? this.client).put<
      SetOAuth2ClientLifespansResponses,
      SetOAuth2ClientLifespansErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await SetOAuth2ClientLifespansRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await SetOAuth2ClientLifespansResponseSchema.parseAsync(data),
      url: "/admin/clients/{id}/lifespans",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Delete JSON Web Key Set
   *
   * Use this endpoint to delete a complete JSON Web Key Set and all the keys in that set.
   *
   * A JSON Web Key (JWK) is a JavaScript Object Notation (JSON) data structure that represents a cryptographic key. A JWK Set is a JSON data structure that represents a set of JWKs. A JSON Web Key is identified by its set and key id. ORY Hydra uses this functionality to store cryptographic keys used for TLS and JSON Web Tokens (such as OpenID Connect ID tokens), and allows storing user-defined keys as well.
   */
  public deleteJsonWebKeySet<ThrowOnError extends boolean = false>(
    options: Options<DeleteJsonWebKeySetRequest, ThrowOnError>,
  ) {
    return (options.client ?? this.client).delete<
      DeleteJsonWebKeySetResponses,
      DeleteJsonWebKeySetErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await DeleteJsonWebKeySetRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await DeleteJsonWebKeySetResponseSchema.parseAsync(data),
      url: "/admin/keys/{set}",
      ...options,
    });
  }

  /**
   * Retrieve a JSON Web Key Set
   *
   * This endpoint can be used to retrieve JWK Sets stored in ORY Hydra.
   *
   * A JSON Web Key (JWK) is a JavaScript Object Notation (JSON) data structure that represents a cryptographic key. A JWK Set is a JSON data structure that represents a set of JWKs. A JSON Web Key is identified by its set and key id. ORY Hydra uses this functionality to store cryptographic keys used for TLS and JSON Web Tokens (such as OpenID Connect ID tokens), and allows storing user-defined keys as well.
   */
  public getJsonWebKeySet<ThrowOnError extends boolean = false>(
    options: Options<GetJsonWebKeySetRequest, ThrowOnError>,
  ) {
    return (options.client ?? this.client).get<
      GetJsonWebKeySetResponses,
      GetJsonWebKeySetErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await GetJsonWebKeySetRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await GetJsonWebKeySetResponseSchema.parseAsync(data),
      url: "/admin/keys/{set}",
      ...options,
    });
  }

  /**
   * Create JSON Web Key
   *
   * This endpoint is capable of generating JSON Web Key Sets for you. There a different strategies available, such as symmetric cryptographic keys (HS256, HS512) and asymetric cryptographic keys (RS256, ECDSA). If the specified JSON Web Key Set does not exist, it will be created.
   *
   * A JSON Web Key (JWK) is a JavaScript Object Notation (JSON) data structure that represents a cryptographic key. A JWK Set is a JSON data structure that represents a set of JWKs. A JSON Web Key is identified by its set and key id. ORY Hydra uses this functionality to store cryptographic keys used for TLS and JSON Web Tokens (such as OpenID Connect ID tokens), and allows storing user-defined keys as well.
   */
  public createJsonWebKeySet<ThrowOnError extends boolean = false>(
    options: Options<CreateJsonWebKeySetRequest, ThrowOnError>,
  ) {
    return (options.client ?? this.client).post<
      CreateJsonWebKeySetResponses,
      CreateJsonWebKeySetErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await CreateJsonWebKeySetRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await CreateJsonWebKeySetResponseSchema.parseAsync(data),
      url: "/admin/keys/{set}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Update a JSON Web Key Set
   *
   * Use this method if you do not want to let Hydra generate the JWKs for you, but instead save your own.
   *
   * A JSON Web Key (JWK) is a JavaScript Object Notation (JSON) data structure that represents a cryptographic key. A JWK Set is a JSON data structure that represents a set of JWKs. A JSON Web Key is identified by its set and key id. ORY Hydra uses this functionality to store cryptographic keys used for TLS and JSON Web Tokens (such as OpenID Connect ID tokens), and allows storing user-defined keys as well.
   */
  public setJsonWebKeySet<ThrowOnError extends boolean = false>(
    options: Options<SetJsonWebKeySetRequest, ThrowOnError>,
  ) {
    return (options.client ?? this.client).put<
      SetJsonWebKeySetResponses,
      SetJsonWebKeySetErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await SetJsonWebKeySetRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await SetJsonWebKeySetResponseSchema.parseAsync(data),
      url: "/admin/keys/{set}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Delete JSON Web Key
   *
   * Use this endpoint to delete a single JSON Web Key.
   *
   * A JSON Web Key (JWK) is a JavaScript Object Notation (JSON) data structure that represents a cryptographic key. A
   * JWK Set is a JSON data structure that represents a set of JWKs. A JSON Web Key is identified by its set and key id. ORY Hydra uses
   * this functionality to store cryptographic keys used for TLS and JSON Web Tokens (such as OpenID Connect ID tokens),
   * and allows storing user-defined keys as well.
   */
  public deleteJsonWebKey<ThrowOnError extends boolean = false>(
    options: Options<DeleteJsonWebKeyRequest, ThrowOnError>,
  ) {
    return (options.client ?? this.client).delete<
      DeleteJsonWebKeyResponses,
      DeleteJsonWebKeyErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await DeleteJsonWebKeyRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await DeleteJsonWebKeyResponseSchema.parseAsync(data),
      url: "/admin/keys/{set}/{kid}",
      ...options,
    });
  }

  /**
   * Get JSON Web Key
   *
   * This endpoint returns a singular JSON Web Key contained in a set. It is identified by the set and the specific key ID (kid).
   */
  public getJsonWebKey<ThrowOnError extends boolean = false>(
    options: Options<GetJsonWebKeyRequest, ThrowOnError>,
  ) {
    return (options.client ?? this.client).get<
      GetJsonWebKeyResponses,
      GetJsonWebKeyErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await GetJsonWebKeyRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await GetJsonWebKeyResponseSchema.parseAsync(data),
      url: "/admin/keys/{set}/{kid}",
      ...options,
    });
  }

  /**
   * Set JSON Web Key
   *
   * Use this method if you do not want to let Hydra generate the JWKs for you, but instead save your own.
   *
   * A JSON Web Key (JWK) is a JavaScript Object Notation (JSON) data structure that represents a cryptographic key. A JWK Set is a JSON data structure that represents a set of JWKs. A JSON Web Key is identified by its set and key id. ORY Hydra uses this functionality to store cryptographic keys used for TLS and JSON Web Tokens (such as OpenID Connect ID tokens), and allows storing user-defined keys as well.
   */
  public setJsonWebKey<ThrowOnError extends boolean = false>(
    options: Options<SetJsonWebKeyRequest, ThrowOnError>,
  ) {
    return (options.client ?? this.client).put<
      SetJsonWebKeyResponses,
      SetJsonWebKeyErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await SetJsonWebKeyRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await SetJsonWebKeyResponseSchema.parseAsync(data),
      url: "/admin/keys/{set}/{kid}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Get OAuth 2.0 Consent Request
   *
   * When an authorization code, hybrid, or implicit OAuth 2.0 Flow is initiated, Ory asks the login provider
   * to authenticate the subject and then tell Ory now about it. If the subject authenticated, he/she must now be asked if
   * the OAuth 2.0 Client which initiated the flow should be allowed to access the resources on the subject's behalf.
   *
   * The consent challenge is appended to the consent provider's URL to which the subject's user-agent (browser) is redirected to. The consent
   * provider uses that challenge to fetch information on the OAuth2 request and then tells Ory if the subject accepted
   * or rejected the request.
   *
   * The default consent provider is available via the Ory Managed Account Experience. To customize the consent provider, please
   * head over to the OAuth 2.0 documentation.
   */
  public getOAuth2ConsentRequest<ThrowOnError extends boolean = false>(
    options: Options<GetOAuth2ConsentRequestRequest, ThrowOnError>,
  ) {
    return (options.client ?? this.client).get<
      GetOAuth2ConsentRequestResponses,
      GetOAuth2ConsentRequestErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await GetOAuth2ConsentRequestRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await GetOAuth2ConsentRequestResponseSchema.parseAsync(data),
      url: "/admin/oauth2/auth/requests/consent",
      ...options,
    });
  }

  /**
   * Accept OAuth 2.0 Consent Request
   *
   * When an authorization code, hybrid, or implicit OAuth 2.0 Flow is initiated, Ory asks the login provider
   * to authenticate the subject and then tell Ory now about it. If the subject authenticated, he/she must now be asked if
   * the OAuth 2.0 Client which initiated the flow should be allowed to access the resources on the subject's behalf.
   *
   * The consent challenge is appended to the consent provider's URL to which the subject's user-agent (browser) is redirected to. The consent
   * provider uses that challenge to fetch information on the OAuth2 request and then tells Ory if the subject accepted
   * or rejected the request.
   *
   * This endpoint tells Ory that the subject has authorized the OAuth 2.0 client to access resources on his/her behalf.
   * The consent provider includes additional information, such as session data for access and ID tokens, and if the
   * consent request should be used as basis for future requests.
   *
   * The response contains a redirect URL which the consent provider should redirect the user-agent to.
   *
   * The default consent provider is available via the Ory Managed Account Experience. To customize the consent provider, please
   * head over to the OAuth 2.0 documentation.
   */
  public acceptOAuth2ConsentRequest<ThrowOnError extends boolean = false>(
    options: Options<AcceptOAuth2ConsentRequestRequest, ThrowOnError>,
  ) {
    return (options.client ?? this.client).put<
      AcceptOAuth2ConsentRequestResponses,
      AcceptOAuth2ConsentRequestErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await AcceptOAuth2ConsentRequestRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await AcceptOAuth2ConsentRequestResponseSchema.parseAsync(data),
      url: "/admin/oauth2/auth/requests/consent/accept",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Reject OAuth 2.0 Consent Request
   *
   * When an authorization code, hybrid, or implicit OAuth 2.0 Flow is initiated, Ory asks the login provider
   * to authenticate the subject and then tell Ory now about it. If the subject authenticated, he/she must now be asked if
   * the OAuth 2.0 Client which initiated the flow should be allowed to access the resources on the subject's behalf.
   *
   * The consent challenge is appended to the consent provider's URL to which the subject's user-agent (browser) is redirected to. The consent
   * provider uses that challenge to fetch information on the OAuth2 request and then tells Ory if the subject accepted
   * or rejected the request.
   *
   * This endpoint tells Ory that the subject has not authorized the OAuth 2.0 client to access resources on his/her behalf.
   * The consent provider must include a reason why the consent was not granted.
   *
   * The response contains a redirect URL which the consent provider should redirect the user-agent to.
   *
   * The default consent provider is available via the Ory Managed Account Experience. To customize the consent provider, please
   * head over to the OAuth 2.0 documentation.
   */
  public rejectOAuth2ConsentRequest<ThrowOnError extends boolean = false>(
    options: Options<RejectOAuth2ConsentRequestRequest, ThrowOnError>,
  ) {
    return (options.client ?? this.client).put<
      RejectOAuth2ConsentRequestResponses,
      RejectOAuth2ConsentRequestErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await RejectOAuth2ConsentRequestRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await RejectOAuth2ConsentRequestResponseSchema.parseAsync(data),
      url: "/admin/oauth2/auth/requests/consent/reject",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Get OAuth 2.0 Login Request
   *
   * When an authorization code, hybrid, or implicit OAuth 2.0 Flow is initiated, Ory asks the login provider
   * to authenticate the subject and then tell the Ory OAuth2 Service about it.
   *
   * Per default, the login provider is Ory itself. You may use a different login provider which needs to be a web-app
   * you write and host, and it must be able to authenticate ("show the subject a login screen")
   * a subject (in OAuth2 the proper name for subject is "resource owner").
   *
   * The authentication challenge is appended to the login provider URL to which the subject's user-agent (browser) is redirected to. The login
   * provider uses that challenge to fetch information on the OAuth2 request and then accept or reject the requested authentication process.
   */
  public getOAuth2LoginRequest<ThrowOnError extends boolean = false>(
    options: Options<GetOAuth2LoginRequestRequest, ThrowOnError>,
  ) {
    return (options.client ?? this.client).get<
      GetOAuth2LoginRequestResponses,
      GetOAuth2LoginRequestErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await GetOAuth2LoginRequestRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await GetOAuth2LoginRequestResponseSchema.parseAsync(data),
      url: "/admin/oauth2/auth/requests/login",
      ...options,
    });
  }

  /**
   * Accept OAuth 2.0 Login Request
   *
   * When an authorization code, hybrid, or implicit OAuth 2.0 Flow is initiated, Ory asks the login provider
   * to authenticate the subject and then tell the Ory OAuth2 Service about it.
   *
   * The authentication challenge is appended to the login provider URL to which the subject's user-agent (browser) is redirected to. The login
   * provider uses that challenge to fetch information on the OAuth2 request and then accept or reject the requested authentication process.
   *
   * This endpoint tells Ory that the subject has successfully authenticated and includes additional information such as
   * the subject's ID and if Ory should remember the subject's subject agent for future authentication attempts by setting
   * a cookie.
   *
   * The response contains a redirect URL which the login provider should redirect the user-agent to.
   */
  public acceptOAuth2LoginRequest<ThrowOnError extends boolean = false>(
    options: Options<AcceptOAuth2LoginRequestRequest, ThrowOnError>,
  ) {
    return (options.client ?? this.client).put<
      AcceptOAuth2LoginRequestResponses,
      AcceptOAuth2LoginRequestErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await AcceptOAuth2LoginRequestRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await AcceptOAuth2LoginRequestResponseSchema.parseAsync(data),
      url: "/admin/oauth2/auth/requests/login/accept",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Reject OAuth 2.0 Login Request
   *
   * When an authorization code, hybrid, or implicit OAuth 2.0 Flow is initiated, Ory asks the login provider
   * to authenticate the subject and then tell the Ory OAuth2 Service about it.
   *
   * The authentication challenge is appended to the login provider URL to which the subject's user-agent (browser) is redirected to. The login
   * provider uses that challenge to fetch information on the OAuth2 request and then accept or reject the requested authentication process.
   *
   * This endpoint tells Ory that the subject has not authenticated and includes a reason why the authentication
   * was denied.
   *
   * The response contains a redirect URL which the login provider should redirect the user-agent to.
   */
  public rejectOAuth2LoginRequest<ThrowOnError extends boolean = false>(
    options: Options<RejectOAuth2LoginRequestRequest, ThrowOnError>,
  ) {
    return (options.client ?? this.client).put<
      RejectOAuth2LoginRequestResponses,
      RejectOAuth2LoginRequestErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await RejectOAuth2LoginRequestRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await RejectOAuth2LoginRequestResponseSchema.parseAsync(data),
      url: "/admin/oauth2/auth/requests/login/reject",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Get OAuth 2.0 Session Logout Request
   *
   * Use this endpoint to fetch an Ory OAuth 2.0 logout request.
   */
  public getOAuth2LogoutRequest<ThrowOnError extends boolean = false>(
    options: Options<GetOAuth2LogoutRequestRequest, ThrowOnError>,
  ) {
    return (options.client ?? this.client).get<
      GetOAuth2LogoutRequestResponses,
      GetOAuth2LogoutRequestErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await GetOAuth2LogoutRequestRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await GetOAuth2LogoutRequestResponseSchema.parseAsync(data),
      url: "/admin/oauth2/auth/requests/logout",
      ...options,
    });
  }

  /**
   * Accept OAuth 2.0 Session Logout Request
   *
   * When a user or an application requests Ory OAuth 2.0 to remove the session state of a subject, this endpoint is used to confirm that logout request.
   *
   * The response contains a redirect URL which the consent provider should redirect the user-agent to.
   */
  public acceptOAuth2LogoutRequest<ThrowOnError extends boolean = false>(
    options: Options<AcceptOAuth2LogoutRequestRequest, ThrowOnError>,
  ) {
    return (options.client ?? this.client).put<
      AcceptOAuth2LogoutRequestResponses,
      AcceptOAuth2LogoutRequestErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await AcceptOAuth2LogoutRequestRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await AcceptOAuth2LogoutRequestResponseSchema.parseAsync(data),
      url: "/admin/oauth2/auth/requests/logout/accept",
      ...options,
    });
  }

  /**
   * Reject OAuth 2.0 Session Logout Request
   *
   * When a user or an application requests Ory OAuth 2.0 to remove the session state of a subject, this endpoint is used to deny that logout request.
   * No HTTP request body is required.
   *
   * The response is empty as the logout provider has to chose what action to perform next.
   */
  public rejectOAuth2LogoutRequest<ThrowOnError extends boolean = false>(
    options: Options<RejectOAuth2LogoutRequestRequest, ThrowOnError>,
  ) {
    return (options.client ?? this.client).put<
      RejectOAuth2LogoutRequestResponses,
      RejectOAuth2LogoutRequestErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await RejectOAuth2LogoutRequestRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await RejectOAuth2LogoutRequestResponseSchema.parseAsync(data),
      url: "/admin/oauth2/auth/requests/logout/reject",
      ...options,
    });
  }

  /**
   * Revoke OAuth 2.0 Consent Sessions of a Subject
   *
   * This endpoint revokes a subject's granted consent sessions and invalidates all
   * associated OAuth 2.0 Access Tokens. You may also only revoke sessions for a specific OAuth 2.0 Client ID.
   */
  public revokeOAuth2ConsentSessions<ThrowOnError extends boolean = false>(
    options: Options<RevokeOAuth2ConsentSessionsRequest, ThrowOnError>,
  ) {
    return (options.client ?? this.client).delete<
      RevokeOAuth2ConsentSessionsResponses,
      RevokeOAuth2ConsentSessionsErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await RevokeOAuth2ConsentSessionsRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await RevokeOAuth2ConsentSessionsResponseSchema.parseAsync(data),
      url: "/admin/oauth2/auth/sessions/consent",
      ...options,
    });
  }

  /**
   * List OAuth 2.0 Consent Sessions of a Subject
   *
   * This endpoint lists all subject's granted consent sessions, including client and granted scope.
   * If the subject is unknown or has not granted any consent sessions yet, the endpoint returns an
   * empty JSON array with status code 200 OK.
   */
  public listOAuth2ConsentSessions<ThrowOnError extends boolean = false>(
    options: Options<ListOAuth2ConsentSessionsRequest, ThrowOnError>,
  ) {
    return (options.client ?? this.client).get<
      ListOAuth2ConsentSessionsResponses,
      ListOAuth2ConsentSessionsErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await ListOAuth2ConsentSessionsRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await ListOAuth2ConsentSessionsResponseSchema.parseAsync(data),
      url: "/admin/oauth2/auth/sessions/consent",
      ...options,
    });
  }

  /**
   * Revokes OAuth 2.0 Login Sessions by either a Subject or a SessionID
   *
   * This endpoint invalidates authentication sessions. After revoking the authentication session(s), the subject
   * has to re-authenticate at the Ory OAuth2 Provider. This endpoint does not invalidate any tokens.
   *
   * If you send the subject in a query param, all authentication sessions that belong to that subject are revoked.
   * No OpenID Connect Front- or Back-channel logout is performed in this case.
   *
   * Alternatively, you can send a SessionID via `sid` query param, in which case, only the session that is connected
   * to that SessionID is revoked. OpenID Connect Back-channel logout is performed in this case.
   *
   * When using Ory for the identity provider, the login provider will also invalidate the session cookie.
   */
  public revokeOAuth2LoginSessions<ThrowOnError extends boolean = false>(
    options?: Options<RevokeOAuth2LoginSessionsRequest, ThrowOnError>,
  ) {
    return (options?.client ?? this.client).delete<
      RevokeOAuth2LoginSessionsResponses,
      RevokeOAuth2LoginSessionsErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await RevokeOAuth2LoginSessionsRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await RevokeOAuth2LoginSessionsResponseSchema.parseAsync(data),
      url: "/admin/oauth2/auth/sessions/login",
      ...options,
    });
  }

  /**
   * Introspect OAuth2 Access and Refresh Tokens
   *
   * The introspection endpoint allows to check if a token (both refresh and access) is active or not. An active token
   * is neither expired nor revoked. If a token is active, additional information on the token will be included. You can
   * set additional data for a token by setting `session.access_token` during the consent flow.
   */
  public introspectOAuth2Token<ThrowOnError extends boolean = false>(
    options?: Options<IntrospectOAuth2TokenRequest, ThrowOnError>,
  ) {
    return (options?.client ?? this.client).post<
      IntrospectOAuth2TokenResponses,
      IntrospectOAuth2TokenErrors,
      ThrowOnError
    >({
      ...urlSearchParamsBodySerializer,
      requestValidator: async (data) =>
        await IntrospectOAuth2TokenRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await IntrospectOAuth2TokenResponseSchema.parseAsync(data),
      url: "/admin/oauth2/introspect",
      ...options,
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
        ...options?.headers,
      },
    });
  }

  /**
   * Delete OAuth 2.0 Access Tokens from specific OAuth 2.0 Client
   *
   * This endpoint deletes OAuth2 access tokens issued to an OAuth 2.0 Client from the database.
   */
  public deleteOAuth2Token<ThrowOnError extends boolean = false>(
    options: Options<DeleteOAuth2TokenRequest, ThrowOnError>,
  ) {
    return (options.client ?? this.client).delete<
      DeleteOAuth2TokenResponses,
      DeleteOAuth2TokenErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await DeleteOAuth2TokenRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await DeleteOAuth2TokenResponseSchema.parseAsync(data),
      url: "/admin/oauth2/tokens",
      ...options,
    });
  }

  /**
   * List Trusted OAuth2 JWT Bearer Grant Type Issuers
   *
   * Use this endpoint to list all trusted JWT Bearer Grant Type Issuers.
   */
  public listTrustedOAuth2JwtGrantIssuers<ThrowOnError extends boolean = false>(
    options?: Options<ListTrustedOAuth2JwtGrantIssuersRequest, ThrowOnError>,
  ) {
    return (options?.client ?? this.client).get<
      ListTrustedOAuth2JwtGrantIssuersResponses,
      ListTrustedOAuth2JwtGrantIssuersErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await ListTrustedOAuth2JwtGrantIssuersRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await ListTrustedOAuth2JwtGrantIssuersResponseSchema.parseAsync(data),
      url: "/admin/trust/grants/jwt-bearer/issuers",
      ...options,
    });
  }

  /**
   * Trust OAuth2 JWT Bearer Grant Type Issuer
   *
   * Use this endpoint to establish a trust relationship for a JWT issuer
   * to perform JSON Web Token (JWT) Profile for OAuth 2.0 Client Authentication
   * and Authorization Grants [RFC7523](https://datatracker.ietf.org/doc/html/rfc7523).
   */
  public trustOAuth2JwtGrantIssuer<ThrowOnError extends boolean = false>(
    options?: Options<TrustOAuth2JwtGrantIssuerRequest, ThrowOnError>,
  ) {
    return (options?.client ?? this.client).post<
      TrustOAuth2JwtGrantIssuerResponses,
      TrustOAuth2JwtGrantIssuerErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await TrustOAuth2JwtGrantIssuerRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await TrustOAuth2JwtGrantIssuerResponseSchema.parseAsync(data),
      url: "/admin/trust/grants/jwt-bearer/issuers",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Delete Trusted OAuth2 JWT Bearer Grant Type Issuer
   *
   * Use this endpoint to delete trusted JWT Bearer Grant Type Issuer. The ID is the one returned when you
   * created the trust relationship.
   *
   * Once deleted, the associated issuer will no longer be able to perform the JSON Web Token (JWT) Profile
   * for OAuth 2.0 Client Authentication and Authorization Grant.
   */
  public deleteTrustedOAuth2JwtGrantIssuer<
    ThrowOnError extends boolean = false,
  >(options: Options<DeleteTrustedOAuth2JwtGrantIssuerRequest, ThrowOnError>) {
    return (options.client ?? this.client).delete<
      DeleteTrustedOAuth2JwtGrantIssuerResponses,
      DeleteTrustedOAuth2JwtGrantIssuerErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await DeleteTrustedOAuth2JwtGrantIssuerRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await DeleteTrustedOAuth2JwtGrantIssuerResponseSchema.parseAsync(data),
      url: "/admin/trust/grants/jwt-bearer/issuers/{id}",
      ...options,
    });
  }

  /**
   * Get Trusted OAuth2 JWT Bearer Grant Type Issuer
   *
   * Use this endpoint to get a trusted JWT Bearer Grant Type Issuer. The ID is the one returned when you
   * created the trust relationship.
   */
  public getTrustedOAuth2JwtGrantIssuer<ThrowOnError extends boolean = false>(
    options: Options<GetTrustedOAuth2JwtGrantIssuerRequest, ThrowOnError>,
  ) {
    return (options.client ?? this.client).get<
      GetTrustedOAuth2JwtGrantIssuerResponses,
      GetTrustedOAuth2JwtGrantIssuerErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await GetTrustedOAuth2JwtGrantIssuerRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await GetTrustedOAuth2JwtGrantIssuerResponseSchema.parseAsync(data),
      url: "/admin/trust/grants/jwt-bearer/issuers/{id}",
      ...options,
    });
  }

  /**
   * Check HTTP Server Status
   *
   * This endpoint returns a HTTP 200 status code when Ory Hydra is accepting incoming
   * HTTP requests. This status does currently not include checks whether the database connection is working.
   *
   * If the service supports TLS Edge Termination, this endpoint does not require the
   * `X-Forwarded-Proto` header to be set.
   *
   * Be aware that if you are running multiple nodes of this service, the health status will never
   * refer to the cluster state, only to a single instance.
   */
  public isAlive<ThrowOnError extends boolean = false>(
    options?: Options<IsAliveRequest, ThrowOnError>,
  ) {
    return (options?.client ?? this.client).get<
      IsAliveResponses,
      IsAliveErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await IsAliveRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await IsAliveResponseSchema.parseAsync(data),
      url: "/health/alive",
      ...options,
    });
  }

  /**
   * Check HTTP Server and Database Status
   *
   * This endpoint returns a HTTP 200 status code when Ory Hydra is up running and the environment dependencies (e.g.
   * the database) are responsive as well.
   *
   * If the service supports TLS Edge Termination, this endpoint does not require the
   * `X-Forwarded-Proto` header to be set.
   *
   * Be aware that if you are running multiple nodes of Ory Hydra, the health status will never
   * refer to the cluster state, only to a single instance.
   */
  public isReady<ThrowOnError extends boolean = false>(
    options?: Options<IsReadyRequest, ThrowOnError>,
  ) {
    return (options?.client ?? this.client).get<
      IsReadyResponses,
      IsReadyErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await IsReadyRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await IsReadyResponseSchema.parseAsync(data),
      url: "/health/ready",
      ...options,
    });
  }

  /**
   * Return Running Software Version.
   *
   * This endpoint returns the version of Ory Hydra.
   *
   * If the service supports TLS Edge Termination, this endpoint does not require the
   * `X-Forwarded-Proto` header to be set.
   *
   * Be aware that if you are running multiple nodes of this service, the version will never
   * refer to the cluster state, only to a single instance.
   */
  public getVersion<ThrowOnError extends boolean = false>(
    options?: Options<GetVersionRequest, ThrowOnError>,
  ) {
    return (options?.client ?? this.client).get<
      GetVersionResponses,
      unknown,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await GetVersionRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await GetVersionResponseSchema.parseAsync(data),
      url: "/version",
      ...options,
    });
  }
}
