# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.4.0
_src_path: gh:radio-aktywne/template-app-next
accountname: radio-aktywne
appname: crocus
description: OIDC auth app 🪪
docs: true
docsurl: https://radio-aktywne.github.io/crocus
envprefix: CROCUS
imagename: apps/crocus
keyprefix: crocus
port: 20020
registry: true
releases: true
reponame: crocus
repourl: https://github.com/radio-aktywne/crocus
